### PR TITLE
Cleanup prisma repo hygiene

### PR DESCRIPTION
**Pull request by TylerJang27**
Move tool definition to linter definition plugin.yaml like the rest of our linters/formatters. Also removes an unnecessary test. I was not able to do this for pmd due to the `run.sh` setup not working as a shim/resolving the binary.

### CODE REVIEW

**Comment by pat-trunk-io** [comment]
Can you still do trunk tools enable prisma?

**Comment by TylerJang27** [comment]
> Can you still do trunk tools enable prisma?

Yep!

**Comment by dapirian** [comment]
Not sure I like this actually - just because it makes it hard (for contributors) to see what tools we support by looking at the repo

**Comment by TylerJang27** [comment]
@dapirian I see your point, although I agree we would have to tweak what we consider worthwhile to be a "standalone" tool. 

Things that would probably fall in that category off the top of my head:
- ansible/ansible-lint
- prisma
- renovate
- sourcery
- terraform
- etc

**Review by pat-trunk-io — APPROVED** [review]

**Comment by TylerJang27** [comment]
Per discussion with David and more offline, closing this in favor of keeping "standalone" tools separate

**Pull request closed without merging**
