### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by error9900**
List `prettier` for additional supported languages.

Supported languages listed here: https://prettier.io/docs/en/

### CODE REVIEW

**Review by EliSchleifer — APPROVED** [review]
LGTM. Thanks

**Comment by TylerJang27** [comment]
Do we want to list those in our README.md if we don't support those filetypes out of the box (all require plugins)?

**Comment by EliSchleifer** [comment]
Any reason not to bring in those plugins by default?

**Comment by TylerJang27** [comment]
I stand corrected. These added file types are all ones we already support. Prettier has some other plugins that support additional filetypes or frameworks, but these are all included in the base and ones that we already have config for.

**Pull request merged**
