### PR TITLE
Add buf generate action

### PR DESCRIPTION
**Pull request by DebkanchanSamadder**

### CODE REVIEW

**Review by EliSchleifer — APPROVED** [review]
LGTM. Can you add the action to the list in the readme.

**Comment by DebkanchanSamadder** [comment]
@EliSchleifer added documentation

**Comment by EliSchleifer** [comment]
Looks like you forked before we got in the githook pieces to make sure everything was formatted pre-push....:)

**Comment by DebkanchanSamadder** [comment]
@EliSchleifer fixed format

**Comment by DebkanchanSamadder** [comment]
wat?? why it removed det from required reviewers??

**Comment by EliSchleifer** [comment]
> wat?? why it removed det from required reviewers??

Maybe it's automatic once we get a single reviewer on the line.

**Review by EliSchleifer — APPROVED** [review]
LGTM

**Comment by DebkanchanSamadder** [comment]
@EliSchleifer merge?

**Pull request merged**
